### ISSUE TITLE
Model.find() no longer accepts a callback in Mongoose

### ISSUE THREAD

**Issue by Maxim-Mazurok** [spring-cloud-samples/spring-cloud-contract-nodejs#29]
Got `[Model.find() no longer accepts a callback in Mongoose](https://stackoverflow.com/questions/75655652/model-find-no-longer-accepts-a-callback-in-mongoose)` error when running `node app`

Fixed by doing `npm install mongoose@4`

**Comment by marcingrzejszczak** [comment]
Hey I don't know much about nodejs, are you willing to file a PR to fix these problems? :grimacing:

**Comment by Maxim-Mazurok** [comment]
Sure, see #31 :)
